TestSam/Models/FizzBuzzData.cs
using System.ComponentModel.DataAnnotations;

namespace FizzBuzz.Web.Models
{
    public class FizzBuzzData
    {
        [Required(ErrorMessage = "*Mandatory")]
        [Range(1, 1000, ErrorMessage = "Invalid number")]
        
        public int UserInput { get; set; }

        public PagedList.IPagedList<string> FizzBuzzList { get; set; }
    }
}

TestSam/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using FizzBuzz.Service;
using FizzBuzz.Web.Models;
using PagedList;

namespace TestSam.Controllers
{
    public class FizzBuzzController : Controller
    {
        private int _pageSize = 20;
        private readonly IFizzBuzzService _fizzBuzzService;

        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            _fizzBuzzService = fizzBuzzService;
        }

        public ActionResult Index()
        {
            return View("Index");
        }

        /// <summary>
        /// Method to get list of numbers in words
        /// </summary>
        /// <param name="txtMaxNumber">user entered max value</param>
        /// <param name="page"></param>
        /// <returns></returns>
        
        public ActionResult GetData(string UserInput, int? page)
        {
            int pageIndex = 1;
            ViewBag.UserInput = Convert.ToInt32(UserInput);
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            List<string> lstWords = _fizzBuzzService.GetFizzBuzzData(Convert.ToInt32(UserInput));

            return View("Index", new FizzBuzzData { FizzBuzzList = lstWords.ToPagedList(pageIndex, _pageSize), UserInput = ViewBag.UserInput});
        }

 
      
    }
}

TestSam/Views/FizzBuzz/Index.cshtml
@using PagedList.Mvc
@model  FizzBuzz.Web.Models.FizzBuzzData
@{
    ViewBag.Title = "Home Page";
}

<div>
    @using (Html.BeginForm("GetData", "FizzBuzz", FormMethod.Post, new { id = "frm1", name = "frm1" }))
    {
        <label>Enter value between 1 to 1000</label>
        @Html.TextBoxFor(m => m.UserInput)
        @Html.ValidationMessageFor(m => m.UserInput, "", new { @class = "fizzerror" })
        <button id="btnSubmit" type="submit">Submit</button>

        if (Model != null)
        {
            <div id="data_grid">
                <table>
                    @foreach (string s in Model.FizzBuzzList.ToList<string>())
                    {
                        <tr>
                            <td>
                                @if (@s == "fizz")
                                {
                                    <span class="fizz">fizz</span>
                                }
                                else if (@s == "buzz")
                                {
                                    <span class="buzz">buzz</span>
                                }
                                else if (@s == "fizz buzz")
                                {
                                    <span class="fizz">fizz</span>@Html.Raw("&nbsp;")<span class="buzz">buzz</span>
                                }
                                else
                                {
                                    @s
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div id="container" style="margin-left: 20px">
                <div class="pagination" style="margin-left: 400px">
                    Page @(Model.FizzBuzzList.PageCount < Model.FizzBuzzList.PageNumber ? 0 : Model.FizzBuzzList.PageNumber) of @Model.FizzBuzzList.PageCount

                    @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("GetData", "FizzBuzz", new { ViewBag.UserInput, page }))
                </div>
            </div>
        }

    }
</div>

TestSam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer><p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

   
   
</body>
</html>